#include <stdint.h>
#include <stm32f446xx.h>
#include <common.h>
#include <port_init.h>

OPERATION_RESULT LCD_PORT_INIT(void){

	OPERATION_RESULT RETVAL;

	if(LCD_COMMAND_PORT_INIT() && LCD_D0D7_LINE_INIT()){
		return RETVAL = OPERATION_SUCCESS;
	}

	else{
		return RETVAL = OPERATION_FAILED;
	}
}

/*
 *	Initialize Port B (PB5, PB6, PB7) for RS, RW, and Enable.
 *	PB5, PB6, and PB7 (OUTPUTS)
 */
OPERATION_RESULT LCD_COMMAND_PORT_INIT(void){

	OPERATION_RESULT RETVAL;

	//Enables GPIO_CLK for GPIOB
	RCC_GPIO_CLK_ENABLE(GPIOB_CLK_EN);

	//Configures PB5, PB6, and PB7 as OUTPUTS
	GPIOB_MODER_SEL(PIN_5, OUTPUT_SEL);	//RS
	GPIOB_MODER_SEL(PIN_6, OUTPUT_SEL);	//RW
	GPIOB_MODER_SEL(PIN_7, OUTPUT_SEL);	//En

	//Initialize all OUTPUT pins for GPIOB as 0
	GPIOB_BSRR_ALL_CLEAR;

	return RETVAL = OPERATION_SUCCESS;
}

/*
 *	Initialize Port C (PC0 - PC7) for D0 - D7 respectively.
 *	PC0 - PC7 (OUTPUTS)
 */
OPERATION_RESULT LCD_D0D7_LINE_INIT(void){

	OPERATION_RESULT RETVAL;

	//Enables GPIO_CLK for GPIOC
	RCC_GPIO_CLK_ENABLE(GPIOC_CLK_EN);

	//Configures PC0 - PC7 as OUTPUTS
	GPIOC_MODER_SEL(PIN_0, OUTPUT_SEL);	//D0
	GPIOC_MODER_SEL(PIN_1, OUTPUT_SEL);	//D1
	GPIOC_MODER_SEL(PIN_2, OUTPUT_SEL);	//D2
	GPIOC_MODER_SEL(PIN_3, OUTPUT_SEL);	//D3
	GPIOC_MODER_SEL(PIN_4, OUTPUT_SEL);	//D4
	GPIOC_MODER_SEL(PIN_5, OUTPUT_SEL);	//D5
	GPIOC_MODER_SEL(PIN_6, OUTPUT_SEL);	//D6
	GPIOC_MODER_SEL(PIN_7, OUTPUT_SEL);	//D7

	//Initialize all OUTPUT pins for GPIOC as 0
	GPIOC_BSRR_ALL_CLEAR;

	return RETVAL = OPERATION_SUCCESS;
}
